spring:
  application:
    name: gateway-server
  cloud:
    config:
      uri: http://localhost:8071
  config:
    import: "configserver:"
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.optimagrowth: DEBUG